export enum RolesEnum {
    DOCENTE = "DOCENTE",
    COORDINADOR = "COORDINADOR",
    SUBDECANO = "SUBDECANO",
    GESTOR_ESPACIOS_FISICOS = "GESTOR_ESPACIOS_FISICOS",
    JEFE_DE_DEPARTAMENTO = "JEFE_DE_DEPARTAMENTO",
}